name: js jest

on:
  workflow_dispatch:
   inputs:
      environment:
        description: 'Environment to run tests against'
        default: develop
        type: choice
        options:
          - develop
          - prod
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: run testcase
        env:
            SECRET: "${{ github.event.inputs.environment == 'prod' && secrets.PRODSECRET || secrets.DEVELOPSECRET}}"
            ENV: "${{ github.event.inputs.environment == 'prod' && 'prod' || 'develop'}}"
        run: |
          yarn build
          yarn test test/LocalSigner.test.ts
          yarn test test/Client.test.ts -env=$ENV -secretKey=$SECRET
        